export enum FruitType {
  RedCherry = "Red Cherry",
  BlackCherry = "Black Cherry",
  Cranberry = "Cranberry",
  CustardApple = "Custard Apple",
  Plum = "Plum",
  DragonFruit = "Dragon Fruit",
  Durian = "Durian",
  BlackGrape = "Black Grape",
  GreenGrape = "Green Grape",
  Grapefruit = "Grapefruit",
  Guava = "Guava",
  Kiwi = "Kiwi",
  Lemon = "Lemon",
  Apple = "Apple",
  Orange = "Orange",
  Pear = "Pear",
  Peach = "Peach",
  PassionFruit = "Passion Fruit",
  Apricot = "Apricot",
  Strawberry = "Strawberry",
  Watermelon = "Watermelon",
  Cantaloupe = "Cantaloupe",
}

export const ALL_FRUIT_TYPES = Object.values(FruitType)

export const FRUIT_IMAGES: Record<FruitType, string> = {
  [FruitType.RedCherry]: "images/fruit/red-cherry.png",
  [FruitType.BlackCherry]: "images/fruit/black-cherry.png",
  [FruitType.Cranberry]: "images/fruit/cranberry.png",
  [FruitType.CustardApple]: "images/fruit/custard-apple.png",
  [FruitType.Plum]: "images/fruit/plum.png",
  [FruitType.DragonFruit]: "images/fruit/dragonfruit.png",
  [FruitType.Durian]: "images/fruit/durian.png",
  [FruitType.BlackGrape]: "images/fruit/black-grape.png",
  [FruitType.GreenGrape]: "images/fruit/green-grape.png",
  [FruitType.Grapefruit]: "images/fruit/grapefruit.png",
  [FruitType.Guava]: "images/fruit/guava.png",
  [FruitType.Kiwi]: "images/fruit/kiwi.png",
  [FruitType.Lemon]: "images/fruit/lemon.png",
  [FruitType.Apple]: "images/fruit/apple.png",
  [FruitType.Orange]: "images/fruit/orange.png",
  [FruitType.Pear]: "images/fruit/pear.png",
  [FruitType.Peach]: "images/fruit/peach.png",
  [FruitType.PassionFruit]: "images/fruit/passionfruit.png",
  [FruitType.Apricot]: "images/fruit/apricot.png",
  [FruitType.Strawberry]: "images/fruit/strawberry.png",
  [FruitType.Watermelon]: "images/fruit/watermelon.png",
  [FruitType.Cantaloupe]: "images/fruit/.png",
}
