export enum FruitType {
  RedCherry = "Red Cherry",
  BlackCherry = "Black Cherry",
  Cranberry = "Cranberry",
  CustardApple = "Custard Apple",
  Plum = "Plum",
  DragonFruit = "Dragon Fruit",
  Durian = "Durian",
  BlackGrape = "Black Grape",
  GreenGrape = "Green Grape",
  Grapefruit = "Grapefruit",
  Guava = "Guava",
  Kiwi = "Kiwi",
  Lemon = "Lemon",
  Apple = "Apple",
  Orange = "Orange",
  Pear = "Pear",
  Peach = "Peach",
  PassionFruit = "Passion Fruit",
  Apricot = "Apricot",
  Strawberry = "Strawberry",
  Watermelon = "Watermelon",
  Cantaloupe = "Cantaloupe",
}

export const ALL_FRUIT_TYPES = Object.values(FruitType)

export const FRUIT_IMAGES: Record<FruitType, string> = {
  [FruitType.RedCherry]: "red-cherry.png",
  [FruitType.BlackCherry]: "black-cherry.png",
  [FruitType.Cranberry]: "cranberry.png",
  [FruitType.CustardApple]: "custard-apple.png",
  [FruitType.Plum]: "plum.png",
  [FruitType.DragonFruit]: "dragonfruit.png",
  [FruitType.Durian]: "durian.png",
  [FruitType.BlackGrape]: "black-grape.png",
  [FruitType.GreenGrape]: "green-grape.png",
  [FruitType.Grapefruit]: "grapefruit.png",
  [FruitType.Guava]: "guava.png",
  [FruitType.Kiwi]: "kiwi.png",
  [FruitType.Lemon]: "lemon.png",
  [FruitType.Apple]: "apple.png",
  [FruitType.Orange]: "orange.png",
  [FruitType.Pear]: "pear.png",
  [FruitType.Peach]: "peach.png",
  [FruitType.PassionFruit]: "passionfruit.png",
  [FruitType.Apricot]: "apricot.png",
  [FruitType.Strawberry]: "strawberry.png",
  [FruitType.Watermelon]: "watermelon.png",
  [FruitType.Cantaloupe]: "cantaloupe.png",
}
